apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vog9s8ro0-python
  janus-idp.io/tekton: vog9s8ro0-python
  backstage.io/kubernetes-id: vog9s8ro0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vog9s8ro0-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
